replicaCount: 5          

bitcoin:
  image:
    repository: cpunet/test
    tag: latest
    pullPolicy: IfNotPresent
  rpc:
    user: braidpool
    password: changeme
  ports:
    p2p: 28333
    rpc: 28332
    zmqHashblock: 38332
    zmqSequence: 38338
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "2Gi"

node:
  image:
    repository: braidpool/node
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    p2p: 6680
    rpc: 6682
    stratum: 3333
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

storage:
  bitcoinDataSize: 10Gi
  braidpoolDataSize: 5Gi
  storageClass: standard    # use 'standard' for minikube

network: cpunet


# VM seed node to bootstrap P2P — your deployed VM
seedNode: "23.111.156.126:28333"