sudo:
    - false

language:
    - cpp

addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - cmake

matrix:
    include:
        - os: osx
          osx_image: xcode12.2
          compiler: clang
          env: LINK=dynamic
        - os: osx
          compiler: clang
          env: LINK=static
        - os: linux
          compiler: clang
          env: LINK=dynamic
        - os: linux
          compiler: clang
          env: LINK=static
          addons:
            apt:
              sources:
                - sourceline: 'ppa:h-rayflood/llvm'
              packages:
                - clang-5.0
        - os: linux
          compiler: gcc
          env: LINK=dynamic
          addons:
            apt:
              packages:
                - g++-4.8
        - os: linux
          compiler: gcc
          env: LINK=static
    fast_finish:
        - true

before_install:

    # Set aliases for readability.
    - if [[ $CC             == gcc     ]]; then GCC=true; fi
    - if [[ $CC             == clang   ]]; then CLANG=true; fi
    - if [[ $LINK           == static  ]]; then STATIC=true; fi
    - if [[ $LINK           == dynamic ]]; then DYNAMIC=true; fi
    - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi
    - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi

install:

    # Export CC/CXX to control compiler/version.
    - if [[ $OSX   && $CLANG && $DYNAMIC ]]; then export CC=clang; export CXX=clang++; fi
    - if [[ $OSX   && $CLANG && $STATIC  ]]; then export CC=clang; export CXX=clang++; fi
    - if [[ $LINUX && $CLANG && $DYNAMIC ]]; then export CC=clang; export CXX=clang++; fi
    - if [[ $LINUX && $CLANG && $STATIC  ]]; then export CC=clang-5.0; export CXX=clang++-5.0; fi
    - if [[ $LINUX && $GCC   && $DYNAMIC ]]; then export CC=gcc-4.8; export CXX=g++-4.8; fi
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then export CC=gcc; export CXX=g++; fi
    # Download and build libbitcoin-database and all dependencies.
    - echo `pwd`
    - git clone https://github.com/libbitcoin/libbitcoin-system.git
    - cd libbitcoin-system
    # - if [[ $OSX   && $CLANG && $DYNAMIC ]]; then CC=$CC CXX=$CXX ./install.sh --enable-isystem --disable-static; fi
    # - if [[ $OSX   && $CLANG && $STATIC  ]]; then CC=$CC CXX=$CXX ./install.sh --enable-isystem --disable-shared --build-boost --prefix=$TRAVIS_BUILD_DIR/my-prefix; fi
    # - if [[ $LINUX && $CLANG && $DYNAMIC ]]; then CC=$CC CXX=$CXX ./install.sh --enable-isystem --build-boost --disable-ndebug --disable-static --prefix=$TRAVIS_BUILD_DIR/my-prefix CFLAGS='-Os' CXXFLAGS='-Os'; fi
    # - if [[ $LINUX && $CLANG && $STATIC  ]]; then CC=$CC CXX=$CXX ./install.sh --enable-isystem --disable-shared --build-boost --prefix=$TRAVIS_BUILD_DIR/my-prefix CFLAGS='-Os' CXXFLAGS='-Os'; fi
    # - if [[ $LINUX && $GCC   && $DYNAMIC ]]; then CC=$CC CXX=$CXX ./install.sh --enable-isystem --disable-static --build-boost --prefix=$TRAVIS_BUILD_DIR/my-prefix CFLAGS='-Os -s' CXXFLAGS='-Os -s'; fi
    # - if [[ $LINUX && $GCC   && $STATIC  ]]; then CC=$CC CXX=$CXX ./install.sh --enable-isystem --build-boost --disable-shared --build-dir=my-build --prefix=$TRAVIS_BUILD_DIR/my-prefix CFLAGS='-Og -g --coverage' CXXFLAGS='-Og -g --coverage'; fi
    - echo `pwd`
    - cd $TRAVIS_BUILD_DIR
    - echo `pwd`
    - ls

    # Download and install packages.

script:

    - mkdir channels/build
    - cd channels/build
    - PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR/my-prefix/lib/pkgconfig/ cmake ../
    - cmake --build .
    - make test

after_success:

    # Download and unpack lcov.
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then wget https://github.com/linux-test-project/lcov/releases/download/v1.12/lcov-1.12.tar.gz; fi
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then tar xzf lcov-1.12.tar.gz; fi
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then cd lcov-1.12; PREFIX="$TRAVIS_BUILD_DIR/my-prefix" make install; cd ..; fi

    # Install coveralls.
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then gem install coveralls-lcov; fi

    # Capture coverage info, filter out system and test code, and debug before upload.
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then $TRAVIS_BUILD_DIR/my-prefix/usr/bin/lcov --directory . --capture --output-file coverage.info; fi
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then $TRAVIS_BUILD_DIR/my-prefix/usr/bin/lcov --remove coverage.info "/usr/*" "$TRAVIS_BUILD_DIR/my-prefix/*" "my-build/*" "test/*" "tools/initchain/*" --output-file coverage.info; fi
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then $TRAVIS_BUILD_DIR/my-prefix/usr/bin/lcov --list coverage.info; fi

    # Upload coverage info to coveralls service (--repo-token <private coveralls repo token>).
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then coveralls-lcov coverage.info; fi

