// Theme types
export type ThemeType = 'dark' | 'light' | 'solarized';

// Base colors mapping for CSS variables
export const colors = {
  // Primary colors
  primary: 'var(--color-primary)',
  primaryLight: 'var(--color-primary-light)',
  primaryDark: 'var(--color-primary-dark)',

  // Secondary colors
  secondary: 'var(--color-secondary)',
  secondaryLight: 'var(--color-secondary-light)',
  secondaryDark: 'var(--color-secondary-dark)',

  // Accent colors
  accent: 'var(--color-accent)',
  accentDark: 'var(--color-accent-dark)',

  // Status colors
  success: 'var(--color-success)',
  error: 'var(--color-error)',
  warning: 'var(--color-warning)',
  info: 'var(--color-info)',

  // UI colors
  background: 'var(--color-background)',
  paper: 'var(--color-paper)',
  cardPaper: 'var(--color-card-paper)',
  surface: 'var(--color-surface)',
  surfaceHover: 'var(--color-surface-hover)',
  border: 'var(--color-border)',
  shadow: 'var(--color-shadow)',
  headerBackground: 'var(--color-header-background)',
  chartBackground: 'var(--color-chart-background)',
  chartLine: 'var(--color-chart-line)',
  chartGrid: 'var(--color-chart-grid)',

  // Text colors
  textPrimary: 'var(--color-text-primary)',
  textSecondary: 'var(--color-text-secondary)',
  textDisabled: 'var(--color-text-disabled)',
  textLight: 'var(--color-text-light)',

  // Element colors
  buttonBackground: 'var(--color-button-background)',
  buttonBackgroundHover: 'var(--color-button-background-hover)',
  buttonText: 'var(--color-button-text)',

  // Card accent colors
  cardAccentPrimary: 'var(--color-card-accent-primary)',
  cardAccentSecondary: 'var(--color-card-accent-secondary)',
  cardAccentSuccess: 'var(--color-card-accent-success)',

  // Special elements
  notification: 'var(--color-notification)',

  // DAG Visualization colors
  tipNode: 'var(--color-tip-node)',
  regularNode: 'var(--color-regular-node)',
  nodeStroke: 'var(--color-node-stroke)',
  linkColor: 'var(--color-link-color)',
  highWorkPathColor: 'var(--color-high-work-path-color)',
};

// Theme definitions
export const themes: Record<ThemeType, Record<string, string>> = {
  dark: {
    '--color-primary': '#3986e8',
    '--color-primary-light': '#64b5f6',
    '--color-primary-dark': '#1565c0',
    '--color-secondary': '#ff9800',
    '--color-secondary-light': '#ffb74d',
    '--color-secondary-dark': '#e65100',
    '--color-accent': '#ffc107',
    '--color-accent-dark': '#e0a800',
    '--color-success': '#4caf50',
    '--color-error': '#f44336',
    '--color-warning': '#ff9800',
    '--color-info': '#2196f3',
    '--color-background': '#121212',
    '--color-paper': '#1e1e1e',
    '--color-card-paper': 'rgba(30, 30, 30, 1)',
    '--color-surface': '#2d2d2d',
    '--color-surface-hover': 'rgba(255,255,255,0.05)',
    '--color-border': 'rgba(255,255,255,0.05)',
    '--color-shadow': 'rgba(0,0,0,0.25)',
    '--color-header-background': '#1a1a1a',
    '--color-chart-background': '#1e1e1e',
    '--color-chart-line': '#ffffff',
    '--color-chart-grid': 'rgba(255,255,255,0.1)',
    '--color-text-primary': '#ffffff',
    '--color-text-secondary': '#b0b0b0',
    '--color-text-disabled': '#686868',
    '--color-text-light': '#ffffff',
    '--color-button-background': '#2d2d2d',
    '--color-button-background-hover': '#3d3d3d',
    '--color-button-text': '#ffffff',
    '--color-card-accent-primary': '#3986e8',
    '--color-card-accent-secondary': '#ff9800',
    '--color-card-accent-success': '#4caf50',
    '--color-notification': '#f8485e',
    '--color-tip-node': '#ff6b6b',
    '--color-regular-node': '#3986e8',
    '--color-node-stroke': '#ffffff',
    '--color-link-color': '#555555',
    '--color-high-work-path-color': '#ff6b6b',
  },
  light: {
    '--color-primary': '#3986e8',
    '--color-primary-light': '#64b5f6',
    '--color-primary-dark': '#1565c0',
    '--color-secondary': '#ff9800',
    '--color-secondary-light': '#ffb74d',
    '--color-secondary-dark': '#e65100',
    '--color-accent': '#ffc107',
    '--color-accent-dark': '#e0a800',
    '--color-success': '#388e3c',
    '--color-error': '#d32f2f',
    '--color-warning': '#f57c00',
    '--color-info': '#1976d2',
    '--color-background': '#f5f5f5',
    '--color-paper': '#ffffff',
    '--color-card-paper': '#fcfcfc',
    '--color-surface': '#e8e8e8',
    '--color-surface-hover': 'rgba(0,0,0,0.05)',
    '--color-border': 'rgba(0,0,0,0.1)',
    '--color-shadow': 'rgba(0,0,0,0.1)',
    '--color-header-background': '#ffffff',
    '--color-chart-background': '#ffffff',
    '--color-chart-line': '#121212',
    '--color-chart-grid': 'rgba(0,0,0,0.1)',
    '--color-text-primary': '#121212',
    '--color-text-secondary': '#5f6368',
    '--color-text-disabled': '#9e9e9e',
    '--color-text-light': '#ffffff',
    '--color-button-background': '#e0e0e0',
    '--color-button-background-hover': '#d5d5d5',
    '--color-button-text': '#000000',
    '--color-card-accent-primary': '#3986e8',
    '--color-card-accent-secondary': '#ff9800',
    '--color-card-accent-success': '#4caf50',
    '--color-notification': '#f44336',
    '--color-tip-node': '#ff6b6b',
    '--color-regular-node': '#3986e8',
    '--color-node-stroke': '#ffffff',
    '--color-link-color': '#999999',
    '--color-high-work-path-color': '#ff6b6b',
  },
  solarized: {
    '--color-primary': '#268bd2',
    '--color-primary-light': '#2aa198',
    '--color-primary-dark': '#268bd2',
    '--color-secondary': '#b58900',
    '--color-secondary-light': '#cb4b16',
    '--color-secondary-dark': '#b58900',
    '--color-accent': '#d33682',
    '--color-accent-dark': '#d33682',
    '--color-success': '#859900',
    '--color-error': '#dc322f',
    '--color-warning': '#b58900',
    '--color-info': '#268bd2',
    '--color-background': '#002b36',
    '--color-paper': '#073642',
    '--color-card-paper': '#0a4052',
    '--color-surface': '#0a4052',
    '--color-surface-hover': 'rgba(147, 161, 161, 0.1)',
    '--color-border': 'rgba(147, 161, 161, 0.2)',
    '--color-shadow': 'rgba(0,0,0,0.2)',
    '--color-header-background': '#073642',
    '--color-chart-background': '#073642',
    '--color-chart-line': '#93a1a1',
    '--color-chart-grid': 'rgba(147, 161, 161, 0.2)',
    '--color-text-primary': '#93a1a1',
    '--color-text-secondary': '#839496',
    '--color-text-disabled': '#586e75',
    '--color-text-light': '#fdf6e3',
    '--color-button-background': '#073642',
    '--color-button-background-hover': '#586e75',
    '--color-button-text': '#93a1a1',
    '--color-card-accent-primary': '#268bd2',
    '--color-card-accent-secondary': '#b58900',
    '--color-card-accent-success': '#859900',
    '--color-notification': '#dc322f',
    '--color-tip-node': '#dc322f',
    '--color-regular-node': '#268bd2',
    '--color-node-stroke': '#fdf6e3',
    '--color-link-color': '#657b83',
    '--color-high-work-path-color': '#dc322f',
  },
};

export default colors;
