regtest=1
server=1
rpcuser=<your_rpc_username>
rpcpassword=securepass123
daemon=1
txindex=1
fallbackfee=0.0002

[regtest]
# RPC
rpcport=18332
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

# P2P 
listen=1
bind=127.0.0.1
port=18444
maxconnections=4

# blocks only
blocksonly=1
mempoolexpiry=1       
dnsseed=0
discover=0
