apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "braidpool.fullname" . }}-config
  labels:
    app: {{ include "braidpool.fullname" . }}
data:
  bitcoin.conf: |
    [cpunet]
    server=1
    rpcuser={{ .Values.bitcoin.rpc.user }}
    rpcpassword={{ .Values.bitcoin.rpc.password }}
    rpcbind=0.0.0.0
    rpcallowip=0.0.0.0/0
    zmqpubsequence=tcp://0.0.0.0:{{ .Values.bitcoin.ports.zmqSequence }}
    zmqpubhashblock=tcp://0.0.0.0:{{ .Values.bitcoin.ports.zmqHashblock }}
    ipcbind=unix:/tmp/bitcoin-ipc/bitcoin.sock
    addnode={{ .Values.seedNode }}
    debug=ipc
    printtoconsole=1