# Regular service — external access to first pod for debugging
apiVersion: v1
kind: Service
metadata:
  name: {{ include "braidpool.fullname" . }}
  labels:
    app: {{ include "braidpool.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "braidpool.fullname" . }}
  ports:
    - name: bitcoin-rpc
      port: {{ .Values.bitcoin.ports.rpc }}
      targetPort: bitcoin-rpc
      nodePort: 30332
    - name: node-rpc
      port: {{ .Values.node.ports.rpc }}
      targetPort: node-rpc
      nodePort: 30682
    - name: stratum
      port: {{ .Values.node.ports.stratum }}
      targetPort: stratum
      nodePort: 30333