# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll"

gem "jekyll-remote-theme"

gem "jekyll-feed"

gem "jekyll-seo-tag"

gem "webrick"

gem "minima"

