# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.2"

gem "jekyll-remote-theme", "~> 0.4.3"

gem "jekyll-feed", "~> 0.15.1"

gem "jekyll-seo-tag", "~> 2.7"

gem "webrick", "~> 1.7"

gem "minima", "~> 2.5"
